export * from './Login'
export * from './About'
export * from './User'
export * from './UserDetails'
export * from './AddEditUser'
export * from './Home'
export * from './Service'
export * from './Contact'